import { useEffect, useMemo, useRef, useState } from "react";

type IconName = "search"|"folder"|"file"|"settings"|"help"|"plus"|"sun"|"moon"|"chevron"|"paperclip"|"send"|"copy"|"refresh"|"like"|"dislike"|"bookmark"|"download"|"sparkle"|"close"|"menu"|"image";
type Source={source:number;document_id?:string;filename?:string;page?:number;chunk_id?:string;distance?:number};
type Message={id:string;role:"user"|"assistant";content:string;sources?:Source[];time?:string};
type Doc={document_id:string;filename:string;total_pages?:number;total_chunks?:number};
type Chat={id:string;title:string;messages:Message[]};
const API=import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000";
const welcome:Message={id:"welcome",role:"assistant",content:"Upload a research paper to start. I can answer questions from indexed papers and show the retrieved pages used for each answer."};
function Icon({name,size=17}:{name:IconName;size?:number}){const p="fill='none' stroke='currentColor' strokeWidth='1.8' strokeLinecap='round' strokeLinejoin='round'";const paths:{[k:string]:string}={search:`<circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/>`,folder:`<path d="M3 6.5h6l2 2h10v9.5H3z"/>`,file:`<path d="M6 2.5h8l4 4v15H6z"/><path d="M14 2.5v4h4"/>`,settings:`<circle cx="12" cy="12" r="3"/><path d="M19 15l1 2-2 2-2-1-2 1-1 2h-2l-1-2-2-1-2 1-2-2 1-2-1-2 1-2-1-2 2-2 2 1 2-1 1-2h2l1 2 2 1 2-1 2 2-1 2 1 2z"/>`,help:`<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.3 2.3 0 1 1 3.9 1.6c-1 .9-1.7 1.2-1.7 2.4"/><path d="M12 16h.01"/>`,plus:`<path d="M12 5v14M5 12h14"/>`,sun:`<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>`,moon:`<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5z"/>`,chevron:`<path d="m8 10 4 4 4-4"/>`,paperclip:`<path d="m20 11-8.5 8.5a5 5 0 0 1-7-7L13 4a3.5 3.5 0 0 1 5 5l-8.5 8.5a2 2 0 0 1-3-3L14 7"/>`,send:`<path d="m3 20 18-8L3 4l3 8z"/><path d="M6 12h15"/>`,copy:`<rect x="8" y="8" width="10" height="11" rx="1"/><path d="M5 16V4a1 1 0 0 1 1-1h9"/>`,refresh:`<path d="M20 11a8 8 0 0 0-14-4L4 9"/><path d="M4 4v5h5"/><path d="M4 13a8 8 0 0 0 14 4l2-2"/><path d="M20 20v-5h-5"/>`,like:`<path d="M7 10v10H4V10zM7 18h8.5a2 2 0 0 0 2-1.6l1-5A2 2 0 0 0 16.5 9H14l.5-3A2 2 0 0 0 12.5 4L9 10H7"/>`,dislike:`<path d="M7 14V4H4v10zM7 6h8.5a2 2 0 0 1 2 1.6l1 5A2 2 0 0 1 16.5 15H14l.5 3a2 2 0 0 1-2 2L9 14H7"/>`,bookmark:`<path d="M6 3h12v18l-6-4-6 4z"/>`,download:`<path d="M12 3v12M7 10l5 5 5-5M4 21h16"/>`,sparkle:`<path d="m12 3 1.3 5.7L19 10l-5.7 1.3L12 17l-1.3-5.7L5 10l5.7-1.3z"/>`,close:`<path d="M6 6l12 12M18 6 6 18"/>`,menu:`<path d="M4 7h16M4 12h16M4 17h16"/>`,image:`<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m5 17 4-4 3 3 2-2 5 4"/>`};return <svg width={size} height={size} viewBox="0 0 24 24" dangerouslySetInnerHTML={{__html:paths[name]}}/>}
function now(){return new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}
export default function App(){
 const[dark,setDark]=useState(()=>localStorage.getItem("rpi-theme")==="dark"),[query,setQuery]=useState(""),[documents,setDocuments]=useState<Doc[]>([]),[selectedDoc,setSelectedDoc]=useState<string>(),[chats,setChats]=useState<Chat[]>([{id:"chat-1",title:"General Analysis",messages:[welcome]}]),[activeChat,setActiveChat]=useState("chat-1"),[tab,setTab]=useState<"chat"|"documents"|"insights">("chat"),[sideTab,setSideTab]=useState<"sources"|"history"|"notes">("sources"),[source,setSource]=useState<Source|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[status,setStatus]=useState("Ready"),[saved,setSaved]=useState<string[]>([]),[image,setImage]=useState<File|null>(null),[workspaceName,setWorkspaceName]=useState("My Research"),[workspaceOpen,setWorkspaceOpen]=useState(false);
 const pdfRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null);
 const chat=chats.find(c=>c.id===activeChat)||chats[0];
 const activeDoc=useMemo(()=>documents.find(d=>d.document_id===selectedDoc),[documents,selectedDoc]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("rpi-theme",dark?"dark":"light")},[dark]);
 async function uploadPdf(file:File){setUploading(true);setStatus("Indexing paper...");try{const f=new FormData();f.append("file",file);const r=await fetch(API+"/upload",{method:"POST",body:f}),d=await r.json();if(!r.ok)throw Error(d.detail||"Upload failed.");const x={document_id:d.document_id,filename:d.filename,total_pages:d.total_pages,total_chunks:d.total_chunks};setDocuments(v=>[...v,x]);setSelectedDoc(x.document_id);setStatus(`Indexed ${d.filename}`)}catch(e){setStatus(e instanceof Error?e.message:"Upload failed.")}finally{setUploading(false)}}
 async function ask(){const text=query.trim();if(!text||busy)return;const user={id:crypto.randomUUID(),role:"user" as const,content:text,time:now()};setChats(v=>v.map(c=>c.id===chat.id?{...c,messages:[...c.messages,user]}:c));setQuery("");setBusy(true);setSource(null);try{const r=await fetch(API+"/query",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text,document_id:selectedDoc,top_k:5})}),d=await r.json();if(!r.ok)throw Error(d.detail||"Query failed.");const assistant={id:crypto.randomUUID(),role:"assistant" as const,content:d.answer,sources:d.sources||[],time:now()};setChats(v=>v.map(c=>c.id===chat.id?{...c,messages:[...c.messages,assistant]}:c));setStatus("Grounded answer generated")}catch(e){const assistant={id:crypto.randomUUID(),role:"assistant" as const,content:e instanceof Error?e.message:"Request failed.",time:now()};setChats(v=>v.map(c=>c.id===chat.id?{...c,messages:[...c.messages,assistant]}:c));setStatus("Request failed")}finally{setBusy(false)}}
 function newChat(){const id=crypto.randomUUID();setChats(v=>[...v,{id,title:"New Research Chat",messages:[welcome]}]);setActiveChat(id);setTab("chat")}
 function exportChat(){const text=chat.messages.map(m=>m.role.toUpperCase()+"\n"+m.content).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download=`${chat.title.replace(/\s+/g,"-").toLowerCase()}.txt`;a.click()}
 function toggleSave(id:string){setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 const allSources=chat.messages.flatMap(m=>m.sources||[]);
 return <div className="app-shell">
  <aside className="sidebar">
   <div className="brand"><div className="brand-icon">⌘</div><div><strong>Research Paper</strong><strong>Intelligence</strong></div></div>
   <button className="new-workspace" onClick={()=>{const n=prompt("Workspace name");if(n?.trim())setWorkspaceName(n.trim())}}><Icon name="plus"/> New Workspace</button>
   <div className="nav-label">WORKSPACES</div>
   <button className="nav-row active"><Icon name="folder"/><span>{workspaceName}</span></button>
   <button className="nav-row"><Icon name="folder"/><span>LLM Research</span></button>
   <button className="nav-row"><Icon name="folder"/><span>Smart Grids</span></button>
   <button className="nav-row"><Icon name="folder"/><span>My Research</span></button>
   <div className="nav-label docs-label">DOCUMENTS <button onClick={()=>pdfRef.current?.click()}><Icon name="plus" size={14}/></button></div>
   <div className="doc-list">{documents.map(d=><button key={d.document_id} className={`nav-doc ${selectedDoc===d.document_id?"selected":""}`} onClick={()=>setSelectedDoc(d.document_id)}><Icon name="file" size={15}/><span>{d.filename}</span></button>)}{!documents.length&&<div className="empty-nav">Upload papers to this workspace.</div>}</div>
   <div className="sidebar-bottom"><button className="nav-row"><Icon name="settings"/><span>Settings</span></button><button className="nav-row"><Icon name="help"/><span>Help & Feedback</span></button></div>
  </aside>
  <section className="main-shell">
   <header className="topbar">
    <div className="workspace-title"><Icon name="folder" size={29}/><div><h2>{workspaceName}</h2><p>{documents.length} Documents <i>·</i> {chats.length} Chats <i>·</i> Active workspace</p></div></div>
    <div className="top-actions"><div className="search"><Icon name="search" size={16}/><input placeholder="Search papers, chats..." value={status==="search"?query:""} onChange={e=>{setStatus("search");setQuery(e.target.value)}}/><span>⌘</span></div><span className="mini-plus">+</span><button className="theme-toggle" onClick={()=>setDark(v=>!v)}><Icon name={dark?"moon":"sun"} size={14}/><span className={dark?"on":""}/></button><div className="profile"><b>PN</b><span>Prajna Deepankar</span><Icon name="chevron" size={13}/></div></div>
   </header>
   <div className="tabs-row"><nav><button className={tab==="chat"?"active":""} onClick={()=>setTab("chat")}>Chat</button><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}>Documents</button><button className={tab==="insights"?"active":""} onClick={()=>setTab("insights")}>Insights</button></nav><div className="chat-controls"><button onClick={newChat}><Icon name="plus" size={14}/> New Chat</button><button onClick={()=>setWorkspaceOpen(v=>!v)}>{chat.title}<Icon name="chevron" size={13}/></button>{workspaceOpen&&<div className="chat-menu">{chats.map(c=><button key={c.id} onClick={()=>{setActiveChat(c.id);setWorkspaceOpen(false)}}>{c.title}</button>)}</div>}</div></div>
   {tab==="chat"&&<div className="chat-layout">
    <section className="conversation"><div className="messages">{chat.messages.map(m=><article className={`message ${m.role}`} key={m.id}><div className="avatar">{m.role==="assistant"?<Icon name="sparkle" size={16}/>: "PN"}</div><div className="message-wrap"><div className="message-author">{m.role==="assistant"?"AI Assistant":"You"} {m.time&&<span>{m.time}</span>}</div><div className="message-card">{m.content}{m.sources?.length?<div className="citations">{m.sources.map(s=><button key={s.source} onClick={()=>setSource(s)}>[SOURCE {s.source}]</button>)}</div>:null}</div>{m.role==="assistant"&&m.id!=="welcome"&&<div className="message-actions"><button onClick={()=>navigator.clipboard?.writeText(m.content)}><Icon name="copy" size={14}/> Copy</button><button onClick={()=>void ask()}><Icon name="refresh" size={13}/> Regenerate</button><button><Icon name="like" size={13}/></button><button><Icon name="dislike" size={13}/></button><button onClick={()=>toggleSave(m.id)} className={saved.includes(m.id)?"saved":""}><Icon name="bookmark" size={13}/></button><button onClick={exportChat}><Icon name="download" size={13}/></button></div>}</div></article>)}{busy&&<article className="message assistant"><div className="avatar"><Icon name="sparkle" size={16}/></div><div className="message-wrap"><div className="message-author">AI Assistant</div><div className="message-card thinking">Retrieving evidence...</div></div></article>}</div>
     <div className="composer-area">{chat.messages.length>1&&<div className="suggestions"><span>Suggested questions:</span>{["What sensors are used?","How is fault detection performed?","What model is used for prediction?","What are the key results?"].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}<div className="composer">{image&&<div className="attachment"><Icon name="image" size={13}/>{image.name}<button onClick={()=>setImage(null)}><Icon name="close" size={12}/></button></div>}<button className="attach" title="Attach PDF" onClick={()=>pdfRef.current?.click()}><Icon name="paperclip"/></button><button className="attach" title="Attach image/screenshot" onClick={()=>imageRef.current?.click()}><Icon name="image"/></button><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="Ask anything about your papers..."/><button className="send" disabled={!query.trim()||busy} onClick={()=>void ask()}><Icon name="send" size={18}/></button></div><small>Answers are grounded in retrieved paper passages. Verify important claims against cited pages.</small></div>
    </section>
    <aside className="evidence"><div className="evidence-tabs"><button className={sideTab==="sources"?"active":""} onClick={()=>setSideTab("sources")}>Sources ({allSources.length})</button><button className={sideTab==="history"?"active":""} onClick={()=>setSideTab("history")}>Chat History</button><button className={sideTab==="notes"?"active":""} onClick={()=>setSideTab("notes")}>Notes</button></div>{sideTab==="sources"&&<div className="evidence-body">{source?<><button className="back" onClick={()=>setSource(null)}>← All Sources</button><div className="source-detail"><b>SOURCE {source.source}</b><h3>{source.filename||"Research paper"}</h3><p>Page {source.page??"?"} · Chunk {source.chunk_id||"—"} · Similarity {source.distance!=null?(1-source.distance).toFixed(2):"—"}</p><div>Source passage preview is available from the retrieved evidence. Full-page viewer will connect to the document endpoint in the backend phase.</div></div></>:allSources.length?allSources.slice().reverse().map((s,i)=><button className="source-card" key={(s.chunk_id||"s")+i} onClick={()=>setSource(s)}><div className="source-head"><b>{i+1}</b><Icon name="file" size={16}/><strong>{s.filename||"Research paper"}</strong></div><p>Page {s.page??"?"} · Chunk {s.chunk_id||"—"} · Similarity {s.distance!=null?(1-s.distance).toFixed(2):"—"}</p><blockquote>Retrieved evidence from this paper supports the answer above.</blockquote><span>View Full Page →</span></button>):<div className="empty-evidence">Sources will appear here after a grounded question is answered.</div>}</div>}{sideTab==="history"&&<div className="history">{chats.map(c=><button key={c.id} onClick={()=>setActiveChat(c.id)}><Icon name="menu" size={14}/><span><b>{c.title}</b><small>{c.messages.length-1} questions</small></span></button>)}</div>}{sideTab==="notes"&&<div className="notes"><textarea placeholder="Add research notes for this workspace..."/><small>Notes will be persisted with the workspace in the backend phase.</small></div>}</aside>
   </div>}
   {tab==="documents"&&<div className="full-tab"><div className="page-heading"><div><em>DOCUMENT LIBRARY</em><h1>Research papers</h1><p>Manage the papers indexed in this workspace.</p></div><button className="primary" onClick={()=>pdfRef.current?.click()}><Icon name="plus" size={15}/> Upload PDF</button></div><div className="document-grid">{documents.map(d=><article key={d.document_id}><Icon name="file" size={28}/><h3>{d.filename}</h3><p>{d.total_pages??"—"} pages · {d.total_chunks??"—"} chunks</p><button onClick={()=>{setSelectedDoc(d.document_id);setTab("chat")}}>Ask about paper</button></article>)}{!documents.length&&<div className="empty-state">No papers yet. Upload a PDF to build your research library.</div>}</div></div>}
   {tab==="insights"&&<div className="full-tab insights"><div className="page-heading"><div><em>RESEARCH INSIGHTS</em><h1>Workspace intelligence</h1><p>Turn your indexed papers into structured research views.</p></div></div><div className="insight-grid"><article><Icon name="sparkle"/><h3>Cross-paper comparison</h3><p>Compare methods, datasets, models and findings across documents.</p></article><article><Icon name="file"/><h3>Evidence map</h3><p>See which papers and pages support the answers in your chats.</p></article><article><Icon name="search"/><h3>Literature signals</h3><p>Surface recurring topics, methods and research gaps from the workspace.</p></article></div></div>}
  </section>
  <input ref={pdfRef} hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&uploadPdf(e.target.files[0])}/>
  <input ref={imageRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f){setImage(f);setStatus("Image attached")}}}/>
 </div>
}