import {useEffect,useRef,useState} from "react";
type Source={source:number;document_id?:string;filename?:string;page?:number;chunk_id?:string};
type Message={id:string;role:"user"|"assistant";content:string;sources?:Source[]};
type Doc={document_id:string;filename:string;total_pages?:number;total_chunks?:number};
const API=import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000";
const welcome:Message={id:"welcome",role:"assistant",content:"Upload a research paper to start. I can answer questions from indexed papers and show the retrieved pages used for each answer."};
export default function App(){
 const[dark,setDark]=useState(()=>localStorage.getItem("rpi-theme")==="dark"),[q,setQ]=useState(""),[msgs,setMsgs]=useState<Message[]>([welcome]),[docs,setDocs]=useState<Doc[]>([]),[doc,setDoc]=useState<string>(),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[status,setStatus]=useState("Ready"),[source,setSource]=useState<Source|null>(null),[saved,setSaved]=useState<string[]>([]);
 const pdf=useRef<HTMLInputElement>(null),img=useRef<HTMLInputElement>(null);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("rpi-theme",dark?"dark":"light")},[dark]);
 async function upload(file:File){setUploading(true);setStatus("Indexing paper...");try{const f=new FormData();f.append("file",file);const r=await fetch(API+"/upload",{method:"POST",body:f}),d=await r.json();if(!r.ok)throw Error(d.detail||"Upload failed");const x={document_id:d.document_id,filename:d.filename,total_pages:d.total_pages,total_chunks:d.total_chunks};setDocs(v=>[...v,x]);setDoc(d.document_id);setStatus("Indexed successfully")}catch(e){setStatus(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false)}}
 async function ask(){const text=q.trim();if(!text||busy)return;setMsgs(v=>[...v,{id:crypto.randomUUID(),role:"user",content:text}]);setQ("");setBusy(true);setSource(null);try{const r=await fetch(API+"/query",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text,document_id:doc,top_k:5})}),d=await r.json();if(!r.ok)throw Error(d.detail||"Query failed");setMsgs(v=>[...v,{id:crypto.randomUUID(),role:"assistant",content:d.answer,sources:d.sources||[]}]);setStatus("Answer generated from retrieved evidence")}catch(e){setMsgs(v=>[...v,{id:crypto.randomUUID(),role:"assistant",content:e instanceof Error?e.message:"Request failed"}]);setStatus("Request failed")}finally{setBusy(false)}}
 function exportChat(){const t=msgs.map(m=>m.role.toUpperCase()+"\n"+m.content).join("\n\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:"text/plain"}));a.download="research-chat.txt";a.click()}
 return <div className="app"><header><div className="brand"><b>R</b><div><strong>Research Intelligence</strong><small>Paper-grounded workspace</small></div></div><div className="head-actions"><span className="status">● {status}</span><button onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button></div></header>
 <main><aside className="left"><label>WORKSPACE <button>+</button></label><div className="active">A&nbsp; Air Quality Research</div><div>R&nbsp; Research Papers</div><label>CHATS <span>2</span></label><div className="active">General Analysis</div><div>Methodology Review</div><label>DOCUMENTS <span>{docs.length}</span></label>{docs.length?docs.map(d=><button className={"doc "+(doc===d.document_id?"sel":"")} key={d.document_id} onClick={()=>setDoc(d.document_id)}><b>PDF</b><span>{d.filename}<small>{d.total_pages??"—"} pages · indexed</small></span></button>):<p className="empty">No papers indexed yet.</p>}<button className="upload" onClick={()=>pdf.current?.click()}>{uploading?"Indexing...":"↑ Upload PDF"}</button><input ref={pdf} hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></aside>
 <section className="chat"><div className="chathead"><div><em>RESEARCH CHAT</em><h1>General Analysis</h1><small>{docs.find(d=>d.document_id===doc)?.filename||"Select a paper to focus retrieval"}</small></div><div><button onClick={exportChat}>Export</button><button onClick={()=>setMsgs([welcome])}>New chat</button></div></div><div className="messages">{msgs.map(m=><article className={m.role} key={m.id}><i>{m.role==="assistant"?"R":"P"}</i><div><small>{m.role==="assistant"?"Research Intelligence":"You"}</small><p>{m.content}</p>{m.sources?.length?<div className="chips">{m.sources.map(s=><button key={s.source} onClick={()=>setSource(s)}>[SOURCE {s.source}] · p.{s.page??"?"}</button>)}</div>:null}{m.role==="assistant"&&m.id!=="welcome"?<nav><button onClick={()=>navigator.clipboard?.writeText(m.content)}>Copy</button><button onClick={()=>setSaved(v=>v.includes(m.id)?v.filter(x=>x!==m.id):[...v,m.id])}>{saved.includes(m.id)?"Saved":"Save"}</button></nav>:null}</div></article>)}{busy&&<article className="assistant"><i>R</i><div><small>Research Intelligence</small><p className="thinking">Retrieving evidence...</p></div></article>}</div><div className="composer"><div className="suggest"><button onClick={()=>setQ("What is the main objective of this research paper?")}>Main objective</button><button onClick={()=>setQ("What are the main components of the proposed framework?")}>Framework</button><button onClick={()=>setQ("What forecasting model is used?")}>Forecasting model</button></div><div className="box"><button onClick={()=>pdf.current?.click()}>📎</button><button onClick={()=>img.current?.click()}>▧</button><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="Ask anything about your research papers..."/><button className="send" disabled={!q.trim()||busy} onClick={()=>void ask()}>↑</button></div><small>Answers are grounded in retrieved paper passages. Verify important claims against cited pages.</small><input ref={img} hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&setStatus("Image selected. Vision analysis will be connected in the next backend phase.")}/></div></section>
 <aside className="right"><em>EVIDENCE</em><h2>{source?"Selected source":"Retrieved sources"}</h2>{source?<div className="selected"><b>SOURCE {source.source}</b><h3>{source.filename||"Research paper"}</h3><small>Page {source.page??"?"}</small><div className="card">Retrieved passage will be displayed here when the source-detail endpoint is added.</div><button onClick={()=>setSource(null)}>Back to sources</button></div>:<><div className="summary">✓ <span><b>Grounded retrieval</b><small>Sources appear after you ask a question.</small></span></div>{msgs.flatMap(m=>m.sources||[]).slice(-5).map((s,i)=><button className="source" key={(s.chunk_id||"s")+i} onClick={()=>setSource(s)}><b>0{i+1} · p.{s.page??"?"}</b><strong>{s.filename||"Research paper"}</strong><small>Retrieved evidence</small></button>)}</>}<div className="note">✦ <span><b>Research tools</b><small>Comparison, OCR and richer source previews can build on this evidence layer.</small></span></div></aside></main></div>
}